/* Algebraic */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#ifdef __cplusplus
extern "C" {
#endif


/* forwarded equations */
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_278(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_279(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_283(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_284(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_288(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_289(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_293(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_294(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_332(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_340(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_364(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_367(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_387(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_390(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_393(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_394(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_408(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_411(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_431(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_434(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_437(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_438(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_443(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_444(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_447(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_448(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_449(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_452(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_453(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_456(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_459(DATA* data);
extern void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_462(DATA* data);

static void functionAlg_system0(DATA *data)
{
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(278);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_278(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(278);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(279);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_279(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(279);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(283);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_283(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(283);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(284);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_284(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(284);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(288);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_288(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(288);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(289);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_289(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(289);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(293);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_293(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(293);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(294);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_294(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(294);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(332);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_332(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(332);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(340);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_340(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(340);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(364);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_364(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(364);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(367);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_367(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(367);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(387);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_387(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(387);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(390);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_390(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(390);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(393);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_393(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(393);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(394);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_394(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(394);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(408);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_408(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(408);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(411);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_411(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(411);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(431);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_431(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(431);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(434);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_434(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(434);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(437);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_437(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(437);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(438);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_438(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(438);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(443);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_443(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(443);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(444);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_444(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(444);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(447);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_447(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(447);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(448);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_448(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(448);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(449);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_449(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(449);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(452);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_452(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(452);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(453);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_453(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(453);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(456);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_456(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(456);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(459);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_459(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(459);
  #endif
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_TICK_EQEXT(462);
  #endif
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_462(data);
  #ifdef _OMC_MEASURE_TIME
    SIM_PROF_ACC_EQEXT(462);
  #endif
}
/* for continuous time variables */
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_functionAlgebraics(DATA *data)
{
  data->simulationInfo.discreteCall = 0;
  functionAlg_system0(data);
  return 0;
}

#ifdef __cplusplus
}
#endif

