/* Non Linear Systems */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_12jac.h"

/*
 equation index: 90
 type: SIMPLE_ASSIGN
 rightHeartBurkhoffWithBusConnector._pulmonicValve._open = rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable > 0.0
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_90(DATA *data)
{
  modelica_boolean tmp1199;
  RELATIONHYSTERESIS(tmp1199, $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable, 0.0, 15, Greater);
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen = tmp1199;
}
/*
 equation index: 91
 type: SIMPLE_ASSIGN
 rightHeartBurkhoffWithBusConnector._pulmonicValve._dp = if rightHeartBurkhoffWithBusConnector.pulmonicValve.open then rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable * modelInputsBlock1.Rpv.k else rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_91(DATA *data)
{
  /* Dummy Line */
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pdp = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen?($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable * $PmodelInputsBlock1$PRpv$Pk):$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable);
}
/*
 equation index: 92
 type: SIMPLE_ASSIGN
 rightHeartBurkhoffWithBusConnector._pulmonicValve._q = if rightHeartBurkhoffWithBusConnector.pulmonicValve.open then rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable else rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable * modelInputsBlock1.Cpv.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_92(DATA *data)
{
  /* Dummy Line */
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pq = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen?$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable:($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable * $PmodelInputsBlock1$PCpv$Pk));
}
/*
 equation index: 93
 type: SIMPLE_ASSIGN
 pulmonaryCirculationBurkhoffWithBusConnector._pulmonaryProximalImpedance._PressureDrop = rightHeartBurkhoffWithBusConnector.pulmonicValve.q * modelInputsBlock1.RcproxPulm.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_93(DATA *data)
{
  $PpulmonaryCirculationBurkhoffWithBusConnector$PpulmonaryProximalImpedance$PPressureDrop = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pq * $PmodelInputsBlock1$PRcproxPulm$Pk);
}
/*
 equation index: 94
 type: SIMPLE_ASSIGN
 MeasurementPulmonaryArtery._pressureFlowMeasurement._P = rightHeartBurkhoffWithBusConnector.RightVentricle.Pressure - rightHeartBurkhoffWithBusConnector.pulmonicValve.dp
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_94(DATA *data)
{
  $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP = ($PrightHeartBurkhoffWithBusConnector$PRightVentricle$PPressure - $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pdp);
}
void initializeStaticNLSData96(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable */
  nlsData->nominal[i] = $P$ATTRIBUTE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable.max;
}

void residualFunc96(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,96).profileBlockIndex,1);
  #endif
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable = xloc[0];
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_90(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_91(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_92(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_93(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_94(data);
  res[0] = ($PpulmonaryCirculationBurkhoffWithBusConnector$PpulmonaryProximalImpedance$PPressureDrop + ($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PPressure - $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP));
}


/*
 equation index: 117
 type: SIMPLE_ASSIGN
 leftHeartBurkhofWithBusConnector._AorticValve._open = leftHeartBurkhofWithBusConnector.AorticValve.passableVariable > 0.0
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_117(DATA *data)
{
  modelica_boolean tmp1200;
  RELATIONHYSTERESIS(tmp1200, $PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable, 0.0, 19, Greater);
  $PleftHeartBurkhofWithBusConnector$PAorticValve$Popen = tmp1200;
}
/*
 equation index: 118
 type: SIMPLE_ASSIGN
 leftHeartBurkhofWithBusConnector._AorticValve._q = if leftHeartBurkhofWithBusConnector.AorticValve.open then leftHeartBurkhofWithBusConnector.AorticValve.passableVariable else leftHeartBurkhofWithBusConnector.AorticValve.passableVariable * modelInputsBlock1.Cav.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_118(DATA *data)
{
  /* Dummy Line */
  $PleftHeartBurkhofWithBusConnector$PAorticValve$Pq = ($PleftHeartBurkhofWithBusConnector$PAorticValve$Popen?$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable:($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable * $PmodelInputsBlock1$PCav$Pk));
}
/*
 equation index: 119
 type: SIMPLE_ASSIGN
 leftHeartBurkhofWithBusConnector._AorticValve._dp = if leftHeartBurkhofWithBusConnector.AorticValve.open then leftHeartBurkhofWithBusConnector.AorticValve.passableVariable * modelInputsBlock1.Rav.k else leftHeartBurkhofWithBusConnector.AorticValve.passableVariable
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_119(DATA *data)
{
  /* Dummy Line */
  $PleftHeartBurkhofWithBusConnector$PAorticValve$Pdp = ($PleftHeartBurkhofWithBusConnector$PAorticValve$Popen?($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable * $PmodelInputsBlock1$PRav$Pk):$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable);
}
/*
 equation index: 120
 type: SIMPLE_ASSIGN
 MeasurementAorta._pressureFlowMeasurement._P = leftHeartBurkhofWithBusConnector.LeftVentricle.Pressure - leftHeartBurkhofWithBusConnector.AorticValve.dp
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_120(DATA *data)
{
  $PMeasurementAorta$PpressureFlowMeasurement$PP = ($PleftHeartBurkhofWithBusConnector$PLeftVentricle$PPressure - $PleftHeartBurkhofWithBusConnector$PAorticValve$Pdp);
}
/*
 equation index: 121
 type: SIMPLE_ASSIGN
 systemicCirculationBurkhoffWithBusConnector._SystemicProximalImpedance._PressureDrop = leftHeartBurkhofWithBusConnector.AorticValve.q * modelInputsBlock1.RcproxSys.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_121(DATA *data)
{
  $PsystemicCirculationBurkhoffWithBusConnector$PSystemicProximalImpedance$PPressureDrop = ($PleftHeartBurkhofWithBusConnector$PAorticValve$Pq * $PmodelInputsBlock1$PRcproxSys$Pk);
}
void initializeStaticNLSData123(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable */
  nlsData->nominal[i] = $P$ATTRIBUTE$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable.max;
}

void residualFunc123(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,123).profileBlockIndex,1);
  #endif
  $PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable = xloc[0];
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_117(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_118(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_119(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_120(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_121(data);
  res[0] = ($PsystemicCirculationBurkhoffWithBusConnector$PSystemicProximalImpedance$PPressureDrop + ($PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PPressure - $PMeasurementAorta$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData127(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc127(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,127).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax - fmax($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax,$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData129(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc129(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,129).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin - fmin($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin,$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData133(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc133(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,133).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax - fmax($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax,$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData135(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc135(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,135).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin - fmin($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin,$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData139(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementAorta$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc139(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,139).profileBlockIndex,1);
  #endif
  $PMeasurementAorta$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementAorta$PpressureFlowMeasurement$PPmax - fmax($PMeasurementAorta$PpressureFlowMeasurement$PPmax,$PMeasurementAorta$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData141(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementAorta$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc141(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,141).profileBlockIndex,1);
  #endif
  $PMeasurementAorta$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementAorta$PpressureFlowMeasurement$PPmin - fmin($PMeasurementAorta$PpressureFlowMeasurement$PPmin,$PMeasurementAorta$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData145(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc145(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,145).profileBlockIndex,1);
  #endif
  $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax - fmax($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax,$PMeasurementCentralVeins$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData147(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc147(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,147).profileBlockIndex,1);
  #endif
  $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin - fmin($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin,$PMeasurementCentralVeins$PpressureFlowMeasurement$PP));
}
void initializeStaticNLSData364(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc364(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,364).profileBlockIndex,1);
  #endif
  $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax - fmax($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmax,$PMeasurementCentralVeins$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData367(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc367(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,367).profileBlockIndex,1);
  #endif
  $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin - fmin($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmin,$PMeasurementCentralVeins$PpressureFlowMeasurement$PP));
}


/*
 equation index: 376
 type: SIMPLE_ASSIGN
 rightHeartBurkhoffWithBusConnector._pulmonicValve._open = rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable > 0.0
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_376(DATA *data)
{
  modelica_boolean tmp1201;
  RELATIONHYSTERESIS(tmp1201, $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable, 0.0, 15, Greater);
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen = tmp1201;
}
/*
 equation index: 377
 type: SIMPLE_ASSIGN
 rightHeartBurkhoffWithBusConnector._pulmonicValve._dp = if rightHeartBurkhoffWithBusConnector.pulmonicValve.open then rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable * modelInputsBlock1.Rpv.k else rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_377(DATA *data)
{
  /* Dummy Line */
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pdp = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen?($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable * $PmodelInputsBlock1$PRpv$Pk):$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable);
}
/*
 equation index: 378
 type: SIMPLE_ASSIGN
 rightHeartBurkhoffWithBusConnector._pulmonicValve._q = if rightHeartBurkhoffWithBusConnector.pulmonicValve.open then rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable else rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable * modelInputsBlock1.Cpv.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_378(DATA *data)
{
  /* Dummy Line */
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pq = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen?$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable:($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable * $PmodelInputsBlock1$PCpv$Pk));
}
/*
 equation index: 379
 type: SIMPLE_ASSIGN
 pulmonaryCirculationBurkhoffWithBusConnector._pulmonaryProximalImpedance._PressureDrop = rightHeartBurkhoffWithBusConnector.pulmonicValve.q * modelInputsBlock1.RcproxPulm.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_379(DATA *data)
{
  $PpulmonaryCirculationBurkhoffWithBusConnector$PpulmonaryProximalImpedance$PPressureDrop = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pq * $PmodelInputsBlock1$PRcproxPulm$Pk);
}
/*
 equation index: 380
 type: SIMPLE_ASSIGN
 MeasurementPulmonaryArtery._pressureFlowMeasurement._P = rightHeartBurkhoffWithBusConnector.RightVentricle.Pressure - rightHeartBurkhoffWithBusConnector.pulmonicValve.dp
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_380(DATA *data)
{
  $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP = ($PrightHeartBurkhoffWithBusConnector$PRightVentricle$PPressure - $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Pdp);
}
void initializeStaticNLSData382(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable */
  nlsData->nominal[i] = $P$ATTRIBUTE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable.max;
}

void residualFunc382(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,382).profileBlockIndex,1);
  #endif
  $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable = xloc[0];
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_376(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_377(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_378(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_379(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_380(data);
  res[0] = ($PpulmonaryCirculationBurkhoffWithBusConnector$PpulmonaryProximalImpedance$PPressureDrop + ($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PPressure - $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData387(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc387(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,387).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax - fmax($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmax,$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData390(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc390(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,390).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin - fmin($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmin,$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData408(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc408(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,408).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax - fmax($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmax,$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData411(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc411(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,411).profileBlockIndex,1);
  #endif
  $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin - fmin($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmin,$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PP));
}


/*
 equation index: 420
 type: SIMPLE_ASSIGN
 leftHeartBurkhofWithBusConnector._AorticValve._open = leftHeartBurkhofWithBusConnector.AorticValve.passableVariable > 0.0
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_420(DATA *data)
{
  modelica_boolean tmp1202;
  RELATIONHYSTERESIS(tmp1202, $PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable, 0.0, 19, Greater);
  $PleftHeartBurkhofWithBusConnector$PAorticValve$Popen = tmp1202;
}
/*
 equation index: 421
 type: SIMPLE_ASSIGN
 leftHeartBurkhofWithBusConnector._AorticValve._dp = if leftHeartBurkhofWithBusConnector.AorticValve.open then leftHeartBurkhofWithBusConnector.AorticValve.passableVariable * modelInputsBlock1.Rav.k else leftHeartBurkhofWithBusConnector.AorticValve.passableVariable
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_421(DATA *data)
{
  /* Dummy Line */
  $PleftHeartBurkhofWithBusConnector$PAorticValve$Pdp = ($PleftHeartBurkhofWithBusConnector$PAorticValve$Popen?($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable * $PmodelInputsBlock1$PRav$Pk):$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable);
}
/*
 equation index: 422
 type: SIMPLE_ASSIGN
 leftHeartBurkhofWithBusConnector._AorticValve._q = if leftHeartBurkhofWithBusConnector.AorticValve.open then leftHeartBurkhofWithBusConnector.AorticValve.passableVariable else leftHeartBurkhofWithBusConnector.AorticValve.passableVariable * modelInputsBlock1.Cav.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_422(DATA *data)
{
  /* Dummy Line */
  $PleftHeartBurkhofWithBusConnector$PAorticValve$Pq = ($PleftHeartBurkhofWithBusConnector$PAorticValve$Popen?$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable:($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable * $PmodelInputsBlock1$PCav$Pk));
}
/*
 equation index: 423
 type: SIMPLE_ASSIGN
 systemicCirculationBurkhoffWithBusConnector._SystemicProximalImpedance._PressureDrop = leftHeartBurkhofWithBusConnector.AorticValve.q * modelInputsBlock1.RcproxSys.k
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_423(DATA *data)
{
  $PsystemicCirculationBurkhoffWithBusConnector$PSystemicProximalImpedance$PPressureDrop = ($PleftHeartBurkhofWithBusConnector$PAorticValve$Pq * $PmodelInputsBlock1$PRcproxSys$Pk);
}
/*
 equation index: 424
 type: SIMPLE_ASSIGN
 MeasurementAorta._pressureFlowMeasurement._P = leftHeartBurkhofWithBusConnector.LeftVentricle.Pressure - leftHeartBurkhofWithBusConnector.AorticValve.dp
 */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_424(DATA *data)
{
  $PMeasurementAorta$PpressureFlowMeasurement$PP = ($PleftHeartBurkhofWithBusConnector$PLeftVentricle$PPressure - $PleftHeartBurkhofWithBusConnector$PAorticValve$Pdp);
}
void initializeStaticNLSData426(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable */
  nlsData->nominal[i] = $P$ATTRIBUTE$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable.max;
}

void residualFunc426(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,426).profileBlockIndex,1);
  #endif
  $PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable = xloc[0];
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_420(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_421(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_422(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_423(data);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_eqFunction_424(data);
  res[0] = ($PsystemicCirculationBurkhoffWithBusConnector$PSystemicProximalImpedance$PPressureDrop + ($PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PPressure - $PMeasurementAorta$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData431(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementAorta$PpressureFlowMeasurement$PPmax */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmax.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmax.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmax.max;
}

void residualFunc431(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,431).profileBlockIndex,1);
  #endif
  $PMeasurementAorta$PpressureFlowMeasurement$PPmax = xloc[0];
  res[0] = ($PMeasurementAorta$PpressureFlowMeasurement$PPmax - fmax($PMeasurementAorta$PpressureFlowMeasurement$PPmax,$PMeasurementAorta$PpressureFlowMeasurement$PP));
}

void initializeStaticNLSData434(void *inData, void *inNlsData)
{
  DATA* data = (DATA*) inData;
  NONLINEAR_SYSTEM_DATA* nlsData = (NONLINEAR_SYSTEM_DATA*) inNlsData;
  int i=0;
  /* static nls data for $PMeasurementAorta$PpressureFlowMeasurement$PPmin */
  nlsData->nominal[i] = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmin.nominal;
  nlsData->min[i]     = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmin.min;
  nlsData->max[i++]   = $P$ATTRIBUTE$PMeasurementAorta$PpressureFlowMeasurement$PPmin.max;
}

void residualFunc434(void* dataIn, double* xloc, double* res, integer* iflag)
{
  DATA* data = (DATA*) dataIn;
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ADD_NCALL_EQ(modelInfoXmlGetEquation(&data->modelData.modelDataXml,434).profileBlockIndex,1);
  #endif
  $PMeasurementAorta$PpressureFlowMeasurement$PPmin = xloc[0];
  res[0] = ($PMeasurementAorta$PpressureFlowMeasurement$PPmin - fmin($PMeasurementAorta$PpressureFlowMeasurement$PPmin,$PMeasurementAorta$PpressureFlowMeasurement$PP));
}

/* funtion initialize non-linear systems */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialNonLinearSystem(NONLINEAR_SYSTEM_DATA* nonLinearSystemData)
{
  nonLinearSystemData[0].equationIndex = 96;
  nonLinearSystemData[0].size = 1;
  nonLinearSystemData[0].method = 0;
  nonLinearSystemData[0].residualFunc = residualFunc96;
  nonLinearSystemData[0].analyticalJacobianColumn = NULL;
  nonLinearSystemData[0].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[0].jacobianIndex = -1;
  nonLinearSystemData[0].initializeStaticNLSData = initializeStaticNLSData96;
  
  
  
  nonLinearSystemData[1].equationIndex = 123;
  nonLinearSystemData[1].size = 1;
  nonLinearSystemData[1].method = 0;
  nonLinearSystemData[1].residualFunc = residualFunc123;
  nonLinearSystemData[1].analyticalJacobianColumn = NULL;
  nonLinearSystemData[1].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[1].jacobianIndex = -1;
  nonLinearSystemData[1].initializeStaticNLSData = initializeStaticNLSData123;
  
  
  
  nonLinearSystemData[2].equationIndex = 127;
  nonLinearSystemData[2].size = 1;
  nonLinearSystemData[2].method = 0;
  nonLinearSystemData[2].residualFunc = residualFunc127;
  nonLinearSystemData[2].analyticalJacobianColumn = NULL;
  nonLinearSystemData[2].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[2].jacobianIndex = -1;
  nonLinearSystemData[2].initializeStaticNLSData = initializeStaticNLSData127;
  
  
  
  nonLinearSystemData[3].equationIndex = 129;
  nonLinearSystemData[3].size = 1;
  nonLinearSystemData[3].method = 0;
  nonLinearSystemData[3].residualFunc = residualFunc129;
  nonLinearSystemData[3].analyticalJacobianColumn = NULL;
  nonLinearSystemData[3].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[3].jacobianIndex = -1;
  nonLinearSystemData[3].initializeStaticNLSData = initializeStaticNLSData129;
  
  
  
  nonLinearSystemData[4].equationIndex = 133;
  nonLinearSystemData[4].size = 1;
  nonLinearSystemData[4].method = 0;
  nonLinearSystemData[4].residualFunc = residualFunc133;
  nonLinearSystemData[4].analyticalJacobianColumn = NULL;
  nonLinearSystemData[4].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[4].jacobianIndex = -1;
  nonLinearSystemData[4].initializeStaticNLSData = initializeStaticNLSData133;
  
  
  
  nonLinearSystemData[5].equationIndex = 135;
  nonLinearSystemData[5].size = 1;
  nonLinearSystemData[5].method = 0;
  nonLinearSystemData[5].residualFunc = residualFunc135;
  nonLinearSystemData[5].analyticalJacobianColumn = NULL;
  nonLinearSystemData[5].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[5].jacobianIndex = -1;
  nonLinearSystemData[5].initializeStaticNLSData = initializeStaticNLSData135;
  
  
  
  nonLinearSystemData[6].equationIndex = 139;
  nonLinearSystemData[6].size = 1;
  nonLinearSystemData[6].method = 0;
  nonLinearSystemData[6].residualFunc = residualFunc139;
  nonLinearSystemData[6].analyticalJacobianColumn = NULL;
  nonLinearSystemData[6].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[6].jacobianIndex = -1;
  nonLinearSystemData[6].initializeStaticNLSData = initializeStaticNLSData139;
  
  
  
  nonLinearSystemData[7].equationIndex = 141;
  nonLinearSystemData[7].size = 1;
  nonLinearSystemData[7].method = 0;
  nonLinearSystemData[7].residualFunc = residualFunc141;
  nonLinearSystemData[7].analyticalJacobianColumn = NULL;
  nonLinearSystemData[7].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[7].jacobianIndex = -1;
  nonLinearSystemData[7].initializeStaticNLSData = initializeStaticNLSData141;
  
  
  
  nonLinearSystemData[8].equationIndex = 145;
  nonLinearSystemData[8].size = 1;
  nonLinearSystemData[8].method = 0;
  nonLinearSystemData[8].residualFunc = residualFunc145;
  nonLinearSystemData[8].analyticalJacobianColumn = NULL;
  nonLinearSystemData[8].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[8].jacobianIndex = -1;
  nonLinearSystemData[8].initializeStaticNLSData = initializeStaticNLSData145;
  
  
  
  nonLinearSystemData[9].equationIndex = 147;
  nonLinearSystemData[9].size = 1;
  nonLinearSystemData[9].method = 0;
  nonLinearSystemData[9].residualFunc = residualFunc147;
  nonLinearSystemData[9].analyticalJacobianColumn = NULL;
  nonLinearSystemData[9].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[9].jacobianIndex = -1;
  nonLinearSystemData[9].initializeStaticNLSData = initializeStaticNLSData147;
  
  nonLinearSystemData[10].equationIndex = 364;
  nonLinearSystemData[10].size = 1;
  nonLinearSystemData[10].method = 0;
  nonLinearSystemData[10].residualFunc = residualFunc364;
  nonLinearSystemData[10].analyticalJacobianColumn = NULL;
  nonLinearSystemData[10].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[10].jacobianIndex = -1;
  nonLinearSystemData[10].initializeStaticNLSData = initializeStaticNLSData364;
  
  
  
  nonLinearSystemData[11].equationIndex = 367;
  nonLinearSystemData[11].size = 1;
  nonLinearSystemData[11].method = 0;
  nonLinearSystemData[11].residualFunc = residualFunc367;
  nonLinearSystemData[11].analyticalJacobianColumn = NULL;
  nonLinearSystemData[11].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[11].jacobianIndex = -1;
  nonLinearSystemData[11].initializeStaticNLSData = initializeStaticNLSData367;
  
  
  
  nonLinearSystemData[12].equationIndex = 382;
  nonLinearSystemData[12].size = 1;
  nonLinearSystemData[12].method = 0;
  nonLinearSystemData[12].residualFunc = residualFunc382;
  nonLinearSystemData[12].analyticalJacobianColumn = NULL;
  nonLinearSystemData[12].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[12].jacobianIndex = -1;
  nonLinearSystemData[12].initializeStaticNLSData = initializeStaticNLSData382;
  
  
  
  nonLinearSystemData[13].equationIndex = 387;
  nonLinearSystemData[13].size = 1;
  nonLinearSystemData[13].method = 0;
  nonLinearSystemData[13].residualFunc = residualFunc387;
  nonLinearSystemData[13].analyticalJacobianColumn = NULL;
  nonLinearSystemData[13].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[13].jacobianIndex = -1;
  nonLinearSystemData[13].initializeStaticNLSData = initializeStaticNLSData387;
  
  
  
  nonLinearSystemData[14].equationIndex = 390;
  nonLinearSystemData[14].size = 1;
  nonLinearSystemData[14].method = 0;
  nonLinearSystemData[14].residualFunc = residualFunc390;
  nonLinearSystemData[14].analyticalJacobianColumn = NULL;
  nonLinearSystemData[14].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[14].jacobianIndex = -1;
  nonLinearSystemData[14].initializeStaticNLSData = initializeStaticNLSData390;
  
  
  
  nonLinearSystemData[15].equationIndex = 408;
  nonLinearSystemData[15].size = 1;
  nonLinearSystemData[15].method = 0;
  nonLinearSystemData[15].residualFunc = residualFunc408;
  nonLinearSystemData[15].analyticalJacobianColumn = NULL;
  nonLinearSystemData[15].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[15].jacobianIndex = -1;
  nonLinearSystemData[15].initializeStaticNLSData = initializeStaticNLSData408;
  
  
  
  nonLinearSystemData[16].equationIndex = 411;
  nonLinearSystemData[16].size = 1;
  nonLinearSystemData[16].method = 0;
  nonLinearSystemData[16].residualFunc = residualFunc411;
  nonLinearSystemData[16].analyticalJacobianColumn = NULL;
  nonLinearSystemData[16].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[16].jacobianIndex = -1;
  nonLinearSystemData[16].initializeStaticNLSData = initializeStaticNLSData411;
  
  
  
  nonLinearSystemData[17].equationIndex = 426;
  nonLinearSystemData[17].size = 1;
  nonLinearSystemData[17].method = 0;
  nonLinearSystemData[17].residualFunc = residualFunc426;
  nonLinearSystemData[17].analyticalJacobianColumn = NULL;
  nonLinearSystemData[17].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[17].jacobianIndex = -1;
  nonLinearSystemData[17].initializeStaticNLSData = initializeStaticNLSData426;
  
  
  
  nonLinearSystemData[18].equationIndex = 431;
  nonLinearSystemData[18].size = 1;
  nonLinearSystemData[18].method = 0;
  nonLinearSystemData[18].residualFunc = residualFunc431;
  nonLinearSystemData[18].analyticalJacobianColumn = NULL;
  nonLinearSystemData[18].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[18].jacobianIndex = -1;
  nonLinearSystemData[18].initializeStaticNLSData = initializeStaticNLSData431;
  
  
  
  nonLinearSystemData[19].equationIndex = 434;
  nonLinearSystemData[19].size = 1;
  nonLinearSystemData[19].method = 0;
  nonLinearSystemData[19].residualFunc = residualFunc434;
  nonLinearSystemData[19].analyticalJacobianColumn = NULL;
  nonLinearSystemData[19].initialAnalyticalJacobian = NULL;
  nonLinearSystemData[19].jacobianIndex = -1;
  nonLinearSystemData[19].initializeStaticNLSData = initializeStaticNLSData434;
  
}


