/* Linearization */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


const char *HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_linear_model_frame()
{
  return "model linear_HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel\n  parameter Integer n = 18; // states \n  parameter Integer k = 0; // top-level inputs \n  parameter Integer l = 0; // top-level outputs \n"
  "  parameter Real x0[18] = {%s};\n"
  "  parameter Real u0[0] = {%s};\n"
  "  parameter Real A[18,18] = [%s];\n"
  "  parameter Real B[18,0] = zeros(18,0);%s\n"
  "  parameter Real C[0,18] = zeros(0,18);%s\n"
  "  parameter Real D[0,0] = zeros(0,0);%s\n"
  "  Real x[18](start=x0);\n"
  "  input Real u[0];\n"
  "  output Real y[0];\n"
  "\n  Real x_PMeasurementCentralVeinsPpressureFlowMeasurementPSumPressure = x[1];\n  Real x_PMeasurementCentralVeinsPpressureFlowMeasurementPVolume = x[2];\n  Real x_PMeasurementAortaPpressureFlowMeasurementPSumPressure = x[3];\n  Real x_PMeasurementAortaPpressureFlowMeasurementPVolume = x[4];\n  Real x_PMeasurementPulmonaryVeinsPpressureFlowMeasurementPSumPressure = x[5];\n  Real x_PMeasurementPulmonaryVeinsPpressureFlowMeasurementPVolume = x[6];\n  Real x_PMeasurementPulmonaryArteryPpressureFlowMeasurementPSumPressure = x[7];\n  Real x_PMeasurementPulmonaryArteryPpressureFlowMeasurementPVolume = x[8];\n  Real x_PsystemicCirculationBurkhoffWithBusConnectorPSystemicVeinsPVolume = x[9];\n  Real x_PsystemicCirculationBurkhoffWithBusConnectorPSystemicArteriesPVolume = x[10];\n  Real x_PsystemicCirculationBurkhoffWithBusConnectorPAortaProximalPVolume = x[11];\n  Real x_PpulmonaryCirculationBurkhoffWithBusConnectorPPulmonaryVeinsPVolume = x[12];\n  Real x_PpulmonaryCirculationBurkhoffWithBusConnectorPPulmonaryArteryPVolume = x[13];\n  Real x_PpulmonaryCirculationBurkhoffWithBusConnectorPPulmonaryArteryProximalPVolume = x[14];\n  Real x_PleftHeartBurkhofWithBusConnectorPLeftVentriclePVolume = x[15];\n  Real x_PleftHeartBurkhofWithBusConnectorPLeftAtriumPVolume = x[16];\n  Real x_PrightHeartBurkhoffWithBusConnectorPRightVentriclePVolume = x[17];\n  Real x_PrightHeartBurkhoffWithBusConnectorPRightAtriumPVolume = x[18];\n      \n"
  "equation\n  der(x) = A * x + B * u;\n  y = C * x + D * u;\nend linear_HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel;\n";
}


