/* Linear Systems */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_12jac.h"

/* initial linear systems */
void setLinearMatrixA42(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, (-($PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Popen?$PmodelInputsBlock1$PRtv$Pk:1.0)), 0, linearSystemData);
}
void setLinearVectorb42(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Pdp);

}

void setLinearMatrixA62(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, (-($PleftHeartBurkhofWithBusConnector$PMitralValve$Popen?$PmodelInputsBlock1$PRmv$Pk:1.0)), 0, linearSystemData);
}
void setLinearVectorb62(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$PleftHeartBurkhofWithBusConnector$PMitralValve$Pdp);

}
/* inline linear systems */
/* parameter linear systems */
/* model linear systems */
void setLinearMatrixA371(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, (-($PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Popen?$PmodelInputsBlock1$PRtv$Pk:1.0)), 0, linearSystemData);
}
void setLinearVectorb371(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Pdp);

}

void setLinearMatrixA415(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, (-($PleftHeartBurkhofWithBusConnector$PMitralValve$Popen?$PmodelInputsBlock1$PRmv$Pk:1.0)), 0, linearSystemData);
}
void setLinearVectorb415(void *inData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->b[0] =  (-$PleftHeartBurkhofWithBusConnector$PMitralValve$Pdp);

}
/* jacobians linear systems */

/* funtion initialize linear systems */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialLinearSystem(LINEAR_SYSTEM_DATA* linearSystemData)
{
  /* initial linear systems */
  linearSystemData[0].equationIndex = 42;
  linearSystemData[0].size = 1;
  linearSystemData[0].nnz = 1;
  linearSystemData[0].setA = setLinearMatrixA42;
  linearSystemData[0].setb = setLinearVectorb42;
  
  linearSystemData[1].equationIndex = 62;
  linearSystemData[1].size = 1;
  linearSystemData[1].nnz = 1;
  linearSystemData[1].setA = setLinearMatrixA62;
  linearSystemData[1].setb = setLinearVectorb62;
  /* inline linear systems */
  /* parameter linear systems */
  /* model linear systems */
  linearSystemData[2].equationIndex = 371;
  linearSystemData[2].size = 1;
  linearSystemData[2].nnz = 1;
  linearSystemData[2].setA = setLinearMatrixA371;
  linearSystemData[2].setb = setLinearVectorb371;
  
  linearSystemData[3].equationIndex = 415;
  linearSystemData[3].size = 1;
  linearSystemData[3].nnz = 1;
  linearSystemData[3].setA = setLinearMatrixA415;
  linearSystemData[3].setb = setLinearVectorb415;
  /* jacobians linear systems */
}


