/* External objects file */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


/* Has to be performed after _init.xml file has been read */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_callExternalObjectConstructors(DATA *data)
{
  /* data->simulationInfo.extObjs = NULL; */
  infoStreamPrint(LOG_DEBUG, 0, "call external Object Constructors");
  infoStreamPrint(LOG_DEBUG, 0, "call external Object Constructors finished");
}

void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_callExternalObjectDestructors(DATA *data)
{
  if(data->simulationInfo.extObjs)
  {
    free(data->simulationInfo.extObjs);
    data->simulationInfo.extObjs = 0;
  }
}

