/* Jacobians */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_12jac.h"
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianG(void* inData)
{
  return 1;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_0(DATA* data, int index)
{
  int i;
  /* write index for cref: $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_1(DATA* data, int index)
{
  int i;
  /* write index for cref: $PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+5] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+6] = $PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] - 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+7] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_2(DATA* data, int index)
{
  int i;
  /* write index for cref: $PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+5] = $PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+6] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_3(DATA* data, int index)
{
  int i;
  /* write index for cref: $PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementAorta$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PMeasurementAorta$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+5] = $PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+6] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+7] = $PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+8] = $PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] - 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+9] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_4(DATA* data, int index)
{
  int i;
  /* write index for cref: $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+5] = $PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+6] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_5(DATA* data, int index)
{
  int i;
  /* write index for cref: $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_6(DATA* data, int index)
{
  int i;
  /* write index for cref: $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] - 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] - 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] - 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] - 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] - 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] - 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+5] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_7(DATA* data, int index)
{
  int i;
  /* write index for cref: $PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PMeasurementAorta$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PMeasurementAorta$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+5] = $PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] - 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+6] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_8(DATA* data, int index)
{
  int i;
  /* write index for cref: $PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] - 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+4] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_9(DATA* data, int index)
{
  int i;
  /* write index for cref: $PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume */
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiff] - 4;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+0] = $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiff] - 4;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+1] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiff] - 4;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+2] = $PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiffed;
  i = data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiff] - 4;
  data->simulationInfo.analyticJacobians[index].sparsePattern.index[i+3] = $PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiffed;
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_10(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PVolume */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_11(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSumPressure */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_12(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PVolume */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_13(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSumPressure */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_14(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementAorta$PpressureFlowMeasurement$PVolume */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_15(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementAorta$PpressureFlowMeasurement$PSumPressure */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_16(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume */
}

static void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_17(DATA* data, int index)
{
  int i;
  /* write index for cref: $PMeasurementCentralVeins$PpressureFlowMeasurement$PSumPressure */
}


int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA(void* inData)
{
  DATA* data = ((DATA*)inData);
  int index = HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_INDEX_JAC_A;
  
  int i;
  
  data->simulationInfo.analyticJacobians[index].sizeCols = 18;
  data->simulationInfo.analyticJacobians[index].sizeRows = 18;
  data->simulationInfo.analyticJacobians[index].seedVars = (modelica_real*) calloc(18,sizeof(modelica_real));
  data->simulationInfo.analyticJacobians[index].resultVars = (modelica_real*) malloc(18*sizeof(modelica_real));
  data->simulationInfo.analyticJacobians[index].tmpVars = (modelica_real*) malloc(0*sizeof(modelica_real));
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex = (unsigned int*) malloc(18*sizeof(int));
  data->simulationInfo.analyticJacobians[index].sparsePattern.index = (unsigned int*) malloc(64*sizeof(int));
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols = (unsigned int*) malloc(18*sizeof(int));
  data->simulationInfo.analyticJacobians[index].sparsePattern.maxColors = 10;
  data->simulationInfo.analyticJacobians[index].jacobian = NULL;
  
  /* write column ptr of compressed sparse column*/
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] = 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] = 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] = 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] = 10;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] = 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] = 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] = 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] = 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] = 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiff] = 4;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementAorta$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementAorta$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 0;
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[$PMeasurementCentralVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 0;
  for(i=1;i<18;++i)
      data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[i] += data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[i-1];
  
  
  /* call functions to write index for each cref */
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_0(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_1(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_2(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_3(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_4(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_5(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_6(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_7(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_8(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_9(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_10(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_11(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_12(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_13(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_14(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_15(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_16(data, index);
  HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianA_17(data, index);
  
  /* write color array */
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PrightHeartBurkhoffWithBusConnector$PRightAtrium$PVolume$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementAorta$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementAorta$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementCentralVeins$PpressureFlowMeasurement$PVolume$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PMeasurementCentralVeins$PpressureFlowMeasurement$PSumPressure$pDERA$indexdiff] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PrightHeartBurkhoffWithBusConnector$PRightVentricle$PVolume$pDERA$indexdiff] = 2;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PleftHeartBurkhofWithBusConnector$PLeftAtrium$PVolume$pDERA$indexdiff] = 3;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PleftHeartBurkhofWithBusConnector$PLeftVentricle$PVolume$pDERA$indexdiff] = 4;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PVolume$pDERA$indexdiff] = 5;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PVolume$pDERA$indexdiff] = 6;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PVolume$pDERA$indexdiff] = 7;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PVolume$pDERA$indexdiff] = 8;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicArteries$PVolume$pDERA$indexdiff] = 9;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[$PsystemicCirculationBurkhoffWithBusConnector$PSystemicVeins$PVolume$pDERA$indexdiff] = 10;
  
  return 0;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianB(void* inData)
{
  return 1;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianC(void* inData)
{
  return 1;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_initialAnalyticJacobianD(void* inData)
{
  return 1;
}

int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_functionJacG_column(void* data)
{
  return 0;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_functionJacA_column(void* inData)
{
  DATA* data = ((DATA*)inData);
  int index = HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_INDEX_JAC_A;
  return 0;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_functionJacB_column(void* data)
{
  return 0;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_functionJacC_column(void* data)
{
  return 0;
}
int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_functionJacD_column(void* data)
{
  return 0;
}


