/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel generated by the OpenModelica Compiler 1.9.1+dev (r18602) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_info_xml.h"
#include "simulation_runtime.h"
#include "omc_error.h"
#include "model_help.h"
#include "delay.h"
#include "linearSystem.h"
#include "nonlinearSystem.h"
#include "mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_functions.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_model.h"
#include "HeamodynamicsDymola.Models.HaedynamicsBurkhoffModel_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_function_initSample(DATA *data)
{
  long i=0;

}

const char *HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"time - pre(heartElasticitiesBurkhoffWithBusConnector.heartInterval1.T0) >= pre(heartElasticitiesBurkhoffWithBusConnector.heartInterval1.HP)",
  "heartElasticitiesBurkhoffWithBusConnector.etTimingAtrial.T0 <= 1.5 * heartElasticitiesBurkhoffWithBusConnector.etTimingAtrial.Tmaxms",
  "heartElasticitiesBurkhoffWithBusConnector.etTimingAtrial.T0 < heartElasticitiesBurkhoffWithBusConnector.heartInterval1.AVDelaySec",
  "heartElasticitiesBurkhoffWithBusConnector.etTimingVentricular.T0 <= 1.5 * heartElasticitiesBurkhoffWithBusConnector.etTimingVentricular.Tmaxms",
  "rightHeartBurkhoffWithBusConnector.RightVentricle.StressedVolume > 0.0",
  "rightHeartBurkhoffWithBusConnector.AtrialElastance.Vs > 0.0",
  "rightHeartBurkhoffWithBusConnector.tricuspidValve.passableVariable > 0.0",
  "time - heartElasticitiesBurkhoffWithBusConnector.heartInterval1.EDTV >= 0.0",
  "abs(rightHeartBurkhoffWithBusConnector.VentricularElastance.Et0 + -1.0) < 0.001",
  "leftHeartBurkhofWithBusConnector.LeftVentricle.StressedVolume > 0.0",
  "leftHeartBurkhofWithBusConnector.AtrialElastance.Vs > 0.0",
  "leftHeartBurkhofWithBusConnector.MitralValve.passableVariable > 0.0",
  "pulmonaryCirculationBurkhoffWithBusConnector.PulmonaryArteryProximal.StressedVolume > 0.0",
  "pulmonaryCirculationBurkhoffWithBusConnector.PulmonaryArtery.StressedVolume > 0.0",
  "pulmonaryCirculationBurkhoffWithBusConnector.PulmonaryVeins.StressedVolume > 0.0",
  "rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable > 0.0",
  "systemicCirculationBurkhoffWithBusConnector.AortaProximal.StressedVolume > 0.0",
  "systemicCirculationBurkhoffWithBusConnector.StressedVolume.u2 > 0.0",
  "systemicCirculationBurkhoffWithBusConnector.StressedVolume.u1 > 0.0",
  "leftHeartBurkhofWithBusConnector.AorticValve.passableVariable > 0.0",
  "time - pre(MeasurementPulmonaryArtery.pressureFlowMeasurement.T0) >= pre(MeasurementPulmonaryArtery.pressureFlowMeasurement.HP)",
  "time - pre(MeasurementPulmonaryVeins.pressureFlowMeasurement.T0) >= pre(MeasurementPulmonaryVeins.pressureFlowMeasurement.HP)",
  "time - pre(MeasurementAorta.pressureFlowMeasurement.T0) >= pre(MeasurementAorta.pressureFlowMeasurement.HP)",
  "time - pre(MeasurementCentralVeins.pressureFlowMeasurement.T0) >= pre(MeasurementCentralVeins.pressureFlowMeasurement.HP)"};
  static const int occurEqs0[] = {1,341};
  static const int occurEqs1[] = {1,345};
  static const int occurEqs2[] = {1,350};
  static const int occurEqs3[] = {1,351};
  static const int occurEqs4[] = {1,353};
  static const int occurEqs5[] = {1,347};
  static const int occurEqs6[] = {1,-1};
  static const int occurEqs7[] = {1,443};
  static const int occurEqs8[] = {1,393};
  static const int occurEqs9[] = {1,398};
  static const int occurEqs10[] = {1,349};
  static const int occurEqs11[] = {1,-1};
  static const int occurEqs12[] = {1,322};
  static const int occurEqs13[] = {1,317};
  static const int occurEqs14[] = {1,314};
  static const int occurEqs15[] = {1,-1};
  static const int occurEqs16[] = {1,307};
  static const int occurEqs17[] = {1,302};
  static const int occurEqs18[] = {1,299};
  static const int occurEqs19[] = {1,-1};
  static const int occurEqs20[] = {1,293};
  static const int occurEqs21[] = {1,288};
  static const int occurEqs22[] = {1,283};
  static const int occurEqs23[] = {1,278};
  static const int *occurEqs[] = {occurEqs0,occurEqs1,occurEqs2,occurEqs3,occurEqs4,occurEqs5,occurEqs6,occurEqs7,occurEqs8,occurEqs9,occurEqs10,occurEqs11,occurEqs12,occurEqs13,occurEqs14,occurEqs15,occurEqs16,occurEqs17,occurEqs18,occurEqs19,occurEqs20,occurEqs21,occurEqs22,occurEqs23};
  *out_EquationIndexes = occurEqs[i];
  return res[i];
}

int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_function_ZeroCrossings(DATA *data, double *gout, double *t)
{
  modelica_boolean tmp1203;
  modelica_boolean tmp1204;
  modelica_boolean tmp1205;
  modelica_boolean tmp1206;
  modelica_boolean tmp1207;
  modelica_boolean tmp1208;
  modelica_boolean tmp1209;
  modelica_boolean tmp1210;
  modelica_boolean tmp1211;
  modelica_boolean tmp1212;
  modelica_boolean tmp1213;
  modelica_boolean tmp1214;
  modelica_boolean tmp1215;
  modelica_boolean tmp1216;
  modelica_boolean tmp1217;
  modelica_boolean tmp1218;
  modelica_boolean tmp1219;
  modelica_boolean tmp1220;
  modelica_boolean tmp1221;
  modelica_boolean tmp1222;
  modelica_boolean tmp1223;
  modelica_boolean tmp1224;
  modelica_boolean tmp1225;
  modelica_boolean tmp1226;

  tmp1203 = GreaterEqZC((time - $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0),$P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP, data->simulationInfo.hysteresisEnabled[0]);
  ZEROCROSSING(0, (tmp1203)?1:-1);
  tmp1204 = LessEqZC($PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PT0,(1.5 * $PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PTmaxms), data->simulationInfo.hysteresisEnabled[1]);
  ZEROCROSSING(1, (tmp1204)?1:-1);
  tmp1205 = LessZC($PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PT0,$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PAVDelaySec, data->simulationInfo.hysteresisEnabled[2]);
  ZEROCROSSING(2, (tmp1205)?1:-1);
  tmp1206 = LessEqZC($PheartElasticitiesBurkhoffWithBusConnector$PetTimingVentricular$PT0,(1.5 * $PheartElasticitiesBurkhoffWithBusConnector$PetTimingVentricular$PTmaxms), data->simulationInfo.hysteresisEnabled[3]);
  ZEROCROSSING(3, (tmp1206)?1:-1);
  tmp1207 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PRightVentricle$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[4]);
  ZEROCROSSING(4, (tmp1207)?1:-1);
  tmp1208 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PAtrialElastance$PVs,0.0, data->simulationInfo.hysteresisEnabled[5]);
  ZEROCROSSING(5, (tmp1208)?1:-1);
  tmp1209 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PtricuspidValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[6]);
  ZEROCROSSING(6, (tmp1209)?1:-1);
  tmp1210 = GreaterEqZC((time - $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV),0.0, data->simulationInfo.hysteresisEnabled[7]);
  ZEROCROSSING(7, (tmp1210)?1:-1);
  tmp1211 = LessZC(fabs(($PrightHeartBurkhoffWithBusConnector$PVentricularElastance$PEt0 + -1.0)),0.001, data->simulationInfo.hysteresisEnabled[8]);
  ZEROCROSSING(8, (tmp1211)?1:-1);
  tmp1212 = GreaterZC($PleftHeartBurkhofWithBusConnector$PLeftVentricle$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[9]);
  ZEROCROSSING(9, (tmp1212)?1:-1);
  tmp1213 = GreaterZC($PleftHeartBurkhofWithBusConnector$PAtrialElastance$PVs,0.0, data->simulationInfo.hysteresisEnabled[10]);
  ZEROCROSSING(10, (tmp1213)?1:-1);
  tmp1214 = GreaterZC($PleftHeartBurkhofWithBusConnector$PMitralValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[11]);
  ZEROCROSSING(11, (tmp1214)?1:-1);
  tmp1215 = GreaterZC($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[12]);
  ZEROCROSSING(12, (tmp1215)?1:-1);
  tmp1216 = GreaterZC($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[13]);
  ZEROCROSSING(13, (tmp1216)?1:-1);
  tmp1217 = GreaterZC($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[14]);
  ZEROCROSSING(14, (tmp1217)?1:-1);
  tmp1218 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[15]);
  ZEROCROSSING(15, (tmp1218)?1:-1);
  tmp1219 = GreaterZC($PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[16]);
  ZEROCROSSING(16, (tmp1219)?1:-1);
  tmp1220 = GreaterZC($PsystemicCirculationBurkhoffWithBusConnector$PStressedVolume$Pu2,0.0, data->simulationInfo.hysteresisEnabled[17]);
  ZEROCROSSING(17, (tmp1220)?1:-1);
  tmp1221 = GreaterZC($PsystemicCirculationBurkhoffWithBusConnector$PStressedVolume$Pu1,0.0, data->simulationInfo.hysteresisEnabled[18]);
  ZEROCROSSING(18, (tmp1221)?1:-1);
  tmp1222 = GreaterZC($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[19]);
  ZEROCROSSING(19, (tmp1222)?1:-1);
  tmp1223 = GreaterEqZC((time - $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[20]);
  ZEROCROSSING(20, (tmp1223)?1:-1);
  tmp1224 = GreaterEqZC((time - $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[21]);
  ZEROCROSSING(21, (tmp1224)?1:-1);
  tmp1225 = GreaterEqZC((time - $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[22]);
  ZEROCROSSING(22, (tmp1225)?1:-1);
  tmp1226 = GreaterEqZC((time - $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[23]);
  ZEROCROSSING(23, (tmp1226)?1:-1);
  
  return 0;
}

const char *HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_relationDescription(int i)
{
  const char *res[] = {"time - pre(heartElasticitiesBurkhoffWithBusConnector.heartInterval1.T0) >= pre(heartElasticitiesBurkhoffWithBusConnector.heartInterval1.HP)",
  "heartElasticitiesBurkhoffWithBusConnector.etTimingAtrial.T0 <= 1.5 * heartElasticitiesBurkhoffWithBusConnector.etTimingAtrial.Tmaxms",
  "heartElasticitiesBurkhoffWithBusConnector.etTimingAtrial.T0 < heartElasticitiesBurkhoffWithBusConnector.heartInterval1.AVDelaySec",
  "heartElasticitiesBurkhoffWithBusConnector.etTimingVentricular.T0 <= 1.5 * heartElasticitiesBurkhoffWithBusConnector.etTimingVentricular.Tmaxms",
  "rightHeartBurkhoffWithBusConnector.RightVentricle.StressedVolume > 0.0",
  "rightHeartBurkhoffWithBusConnector.AtrialElastance.Vs > 0.0",
  "rightHeartBurkhoffWithBusConnector.tricuspidValve.passableVariable > 0.0",
  "time - heartElasticitiesBurkhoffWithBusConnector.heartInterval1.EDTV >= 0.0",
  "abs(rightHeartBurkhoffWithBusConnector.VentricularElastance.Et0 + -1.0) < 0.001",
  "leftHeartBurkhofWithBusConnector.LeftVentricle.StressedVolume > 0.0",
  "leftHeartBurkhofWithBusConnector.AtrialElastance.Vs > 0.0",
  "leftHeartBurkhofWithBusConnector.MitralValve.passableVariable > 0.0",
  "pulmonaryCirculationBurkhoffWithBusConnector.PulmonaryArteryProximal.StressedVolume > 0.0",
  "pulmonaryCirculationBurkhoffWithBusConnector.PulmonaryArtery.StressedVolume > 0.0",
  "pulmonaryCirculationBurkhoffWithBusConnector.PulmonaryVeins.StressedVolume > 0.0",
  "rightHeartBurkhoffWithBusConnector.pulmonicValve.passableVariable > 0.0",
  "systemicCirculationBurkhoffWithBusConnector.AortaProximal.StressedVolume > 0.0",
  "systemicCirculationBurkhoffWithBusConnector.StressedVolume.u2 > 0.0",
  "systemicCirculationBurkhoffWithBusConnector.StressedVolume.u1 > 0.0",
  "leftHeartBurkhofWithBusConnector.AorticValve.passableVariable > 0.0",
  "time - pre(MeasurementPulmonaryArtery.pressureFlowMeasurement.T0) >= pre(MeasurementPulmonaryArtery.pressureFlowMeasurement.HP)",
  "time - pre(MeasurementPulmonaryVeins.pressureFlowMeasurement.T0) >= pre(MeasurementPulmonaryVeins.pressureFlowMeasurement.HP)",
  "time - pre(MeasurementAorta.pressureFlowMeasurement.T0) >= pre(MeasurementAorta.pressureFlowMeasurement.HP)",
  "time - pre(MeasurementCentralVeins.pressureFlowMeasurement.T0) >= pre(MeasurementCentralVeins.pressureFlowMeasurement.HP)"};
  return res[i];
};

int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_function_updateRelations(DATA *data, int evalforZeroCross)
{
  modelica_boolean tmp1227;
  modelica_boolean tmp1228;
  modelica_boolean tmp1229;
  modelica_boolean tmp1230;
  modelica_boolean tmp1231;
  modelica_boolean tmp1232;
  modelica_boolean tmp1233;
  modelica_boolean tmp1234;
  modelica_boolean tmp1235;
  modelica_boolean tmp1236;
  modelica_boolean tmp1237;
  modelica_boolean tmp1238;
  modelica_boolean tmp1239;
  modelica_boolean tmp1240;
  modelica_boolean tmp1241;
  modelica_boolean tmp1242;
  modelica_boolean tmp1243;
  modelica_boolean tmp1244;
  modelica_boolean tmp1245;
  modelica_boolean tmp1246;
  modelica_boolean tmp1247;
  modelica_boolean tmp1248;
  modelica_boolean tmp1249;
  modelica_boolean tmp1250;
  
  if(evalforZeroCross)
  {
    tmp1227 = GreaterEqZC((time - $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0),$P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP, data->simulationInfo.hysteresisEnabled[0]);
    data->simulationInfo.relations[0] = tmp1227;
    tmp1228 = LessEqZC($PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PT0,(1.5 * $PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PTmaxms), data->simulationInfo.hysteresisEnabled[1]);
    data->simulationInfo.relations[1] = tmp1228;
    tmp1229 = LessZC($PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PT0,$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PAVDelaySec, data->simulationInfo.hysteresisEnabled[2]);
    data->simulationInfo.relations[2] = tmp1229;
    tmp1230 = LessEqZC($PheartElasticitiesBurkhoffWithBusConnector$PetTimingVentricular$PT0,(1.5 * $PheartElasticitiesBurkhoffWithBusConnector$PetTimingVentricular$PTmaxms), data->simulationInfo.hysteresisEnabled[3]);
    data->simulationInfo.relations[3] = tmp1230;
    tmp1231 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PRightVentricle$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[4]);
    data->simulationInfo.relations[4] = tmp1231;
    tmp1232 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PAtrialElastance$PVs,0.0, data->simulationInfo.hysteresisEnabled[5]);
    data->simulationInfo.relations[5] = tmp1232;
    tmp1233 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PtricuspidValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[6]);
    data->simulationInfo.relations[6] = tmp1233;
    tmp1234 = GreaterEqZC((time - $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV),0.0, data->simulationInfo.hysteresisEnabled[7]);
    data->simulationInfo.relations[7] = tmp1234;
    tmp1235 = LessZC(fabs(($PrightHeartBurkhoffWithBusConnector$PVentricularElastance$PEt0 + -1.0)),0.001, data->simulationInfo.hysteresisEnabled[8]);
    data->simulationInfo.relations[8] = tmp1235;
    tmp1236 = GreaterZC($PleftHeartBurkhofWithBusConnector$PLeftVentricle$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[9]);
    data->simulationInfo.relations[9] = tmp1236;
    tmp1237 = GreaterZC($PleftHeartBurkhofWithBusConnector$PAtrialElastance$PVs,0.0, data->simulationInfo.hysteresisEnabled[10]);
    data->simulationInfo.relations[10] = tmp1237;
    tmp1238 = GreaterZC($PleftHeartBurkhofWithBusConnector$PMitralValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[11]);
    data->simulationInfo.relations[11] = tmp1238;
    tmp1239 = GreaterZC($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[12]);
    data->simulationInfo.relations[12] = tmp1239;
    tmp1240 = GreaterZC($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[13]);
    data->simulationInfo.relations[13] = tmp1240;
    tmp1241 = GreaterZC($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[14]);
    data->simulationInfo.relations[14] = tmp1241;
    tmp1242 = GreaterZC($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[15]);
    data->simulationInfo.relations[15] = tmp1242;
    tmp1243 = GreaterZC($PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PStressedVolume,0.0, data->simulationInfo.hysteresisEnabled[16]);
    data->simulationInfo.relations[16] = tmp1243;
    tmp1244 = GreaterZC($PsystemicCirculationBurkhoffWithBusConnector$PStressedVolume$Pu2,0.0, data->simulationInfo.hysteresisEnabled[17]);
    data->simulationInfo.relations[17] = tmp1244;
    tmp1245 = GreaterZC($PsystemicCirculationBurkhoffWithBusConnector$PStressedVolume$Pu1,0.0, data->simulationInfo.hysteresisEnabled[18]);
    data->simulationInfo.relations[18] = tmp1245;
    tmp1246 = GreaterZC($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable,0.0, data->simulationInfo.hysteresisEnabled[19]);
    data->simulationInfo.relations[19] = tmp1246;
    tmp1247 = GreaterEqZC((time - $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[20]);
    data->simulationInfo.relations[20] = tmp1247;
    tmp1248 = GreaterEqZC((time - $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[21]);
    data->simulationInfo.relations[21] = tmp1248;
    tmp1249 = GreaterEqZC((time - $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[22]);
    data->simulationInfo.relations[22] = tmp1249;
    tmp1250 = GreaterEqZC((time - $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PT0),$P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PHP, data->simulationInfo.hysteresisEnabled[23]);
    data->simulationInfo.relations[23] = tmp1250;
  }
  else
  {
    data->simulationInfo.relations[0] = ((time - $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0) >= $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP);
    data->simulationInfo.relations[1] = ($PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PT0 <= (1.5 * $PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PTmaxms));
    data->simulationInfo.relations[2] = ($PheartElasticitiesBurkhoffWithBusConnector$PetTimingAtrial$PT0 < $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PAVDelaySec);
    data->simulationInfo.relations[3] = ($PheartElasticitiesBurkhoffWithBusConnector$PetTimingVentricular$PT0 <= (1.5 * $PheartElasticitiesBurkhoffWithBusConnector$PetTimingVentricular$PTmaxms));
    data->simulationInfo.relations[4] = ($PrightHeartBurkhoffWithBusConnector$PRightVentricle$PStressedVolume > 0.0);
    data->simulationInfo.relations[5] = ($PrightHeartBurkhoffWithBusConnector$PAtrialElastance$PVs > 0.0);
    data->simulationInfo.relations[6] = ($PrightHeartBurkhoffWithBusConnector$PtricuspidValve$PpassableVariable > 0.0);
    data->simulationInfo.relations[7] = ((time - $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV) >= 0.0);
    data->simulationInfo.relations[8] = (fabs(($PrightHeartBurkhoffWithBusConnector$PVentricularElastance$PEt0 + -1.0)) < 0.001);
    data->simulationInfo.relations[9] = ($PleftHeartBurkhofWithBusConnector$PLeftVentricle$PStressedVolume > 0.0);
    data->simulationInfo.relations[10] = ($PleftHeartBurkhofWithBusConnector$PAtrialElastance$PVs > 0.0);
    data->simulationInfo.relations[11] = ($PleftHeartBurkhofWithBusConnector$PMitralValve$PpassableVariable > 0.0);
    data->simulationInfo.relations[12] = ($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArteryProximal$PStressedVolume > 0.0);
    data->simulationInfo.relations[13] = ($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryArtery$PStressedVolume > 0.0);
    data->simulationInfo.relations[14] = ($PpulmonaryCirculationBurkhoffWithBusConnector$PPulmonaryVeins$PStressedVolume > 0.0);
    data->simulationInfo.relations[15] = ($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$PpassableVariable > 0.0);
    data->simulationInfo.relations[16] = ($PsystemicCirculationBurkhoffWithBusConnector$PAortaProximal$PStressedVolume > 0.0);
    data->simulationInfo.relations[17] = ($PsystemicCirculationBurkhoffWithBusConnector$PStressedVolume$Pu2 > 0.0);
    data->simulationInfo.relations[18] = ($PsystemicCirculationBurkhoffWithBusConnector$PStressedVolume$Pu1 > 0.0);
    data->simulationInfo.relations[19] = ($PleftHeartBurkhofWithBusConnector$PAorticValve$PpassableVariable > 0.0);
    data->simulationInfo.relations[20] = ((time - $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0) >= $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP);
    data->simulationInfo.relations[21] = ((time - $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0) >= $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP);
    data->simulationInfo.relations[22] = ((time - $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PT0) >= $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PHP);
    data->simulationInfo.relations[23] = ((time - $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PT0) >= $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PHP);
  }
  
  return 0;
}

int HeamodynamicsDymola_Models_HaedynamicsBurkhoffModel_checkForDiscreteChanges(DATA *data)
{
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes");
  if($P$whenCondition9 != $P$PRE$P$whenCondition9)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition9 from %d to %d", $P$PRE$P$whenCondition9, $P$whenCondition9);
    needToIterate = 1;
  }
  if($P$whenCondition8 != $P$PRE$P$whenCondition8)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition8 from %d to %d", $P$PRE$P$whenCondition8, $P$whenCondition8);
    needToIterate = 1;
  }
  if($P$whenCondition7 != $P$PRE$P$whenCondition7)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition7 from %d to %d", $P$PRE$P$whenCondition7, $P$whenCondition7);
    needToIterate = 1;
  }
  if($P$whenCondition6 != $P$PRE$P$whenCondition6)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition6 from %d to %d", $P$PRE$P$whenCondition6, $P$whenCondition6);
    needToIterate = 1;
  }
  if($P$whenCondition5 != $P$PRE$P$whenCondition5)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition5 from %d to %d", $P$PRE$P$whenCondition5, $P$whenCondition5);
    needToIterate = 1;
  }
  if($P$whenCondition4 != $P$PRE$P$whenCondition4)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition4 from %d to %d", $P$PRE$P$whenCondition4, $P$whenCondition4);
    needToIterate = 1;
  }
  if($P$whenCondition3 != $P$PRE$P$whenCondition3)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition3 from %d to %d", $P$PRE$P$whenCondition3, $P$whenCondition3);
    needToIterate = 1;
  }
  if($P$whenCondition2 != $P$PRE$P$whenCondition2)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition2 from %d to %d", $P$PRE$P$whenCondition2, $P$whenCondition2);
    needToIterate = 1;
  }
  if($P$whenCondition1 != $P$PRE$P$whenCondition1)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition1 from %d to %d", $P$PRE$P$whenCondition1, $P$whenCondition1);
    needToIterate = 1;
  }
  if($PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP != $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: heartElasticitiesBurkhoffWithBusConnector._heartInterval1._HP from %g to %g", $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP, $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PHP);
    needToIterate = 1;
  }
  if($PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$Pb != $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: heartElasticitiesBurkhoffWithBusConnector._heartInterval1._b from %d to %d", $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$Pb, $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$Pb);
    needToIterate = 1;
  }
  if($PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0 != $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: heartElasticitiesBurkhoffWithBusConnector._heartInterval1._T0 from %g to %g", $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0, $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PT0);
    needToIterate = 1;
  }
  if($PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV != $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: heartElasticitiesBurkhoffWithBusConnector._heartInterval1._EDTV from %g to %g", $P$PRE$PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV, $PheartElasticitiesBurkhoffWithBusConnector$PheartInterval1$PEDTV);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Popen != $P$PRE$PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Popen)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._tricuspidValve._open from %d to %d", $P$PRE$PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Popen, $PrightHeartBurkhoffWithBusConnector$PtricuspidValve$Popen);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen != $P$PRE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._pulmonicValve._open from %d to %d", $P$PRE$PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen, $PrightHeartBurkhoffWithBusConnector$PpulmonicValve$Popen);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESV != $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._ventricularEndIntervals._ESV from %g to %g", $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESV, $PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESV);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESP != $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._ventricularEndIntervals._ESP from %g to %g", $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESP, $PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PESP);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDV != $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._ventricularEndIntervals._EDV from %g to %g", $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDV, $PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDV);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDP != $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._ventricularEndIntervals._EDP from %g to %g", $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDP, $PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$PEDP);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pb != $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._ventricularEndIntervals._b from %d to %d", $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pb, $PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pb);
    needToIterate = 1;
  }
  if($PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pbb != $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pbb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: rightHeartBurkhoffWithBusConnector._ventricularEndIntervals._bb from %d to %d", $P$PRE$PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pbb, $PrightHeartBurkhoffWithBusConnector$PventricularEndIntervals$Pbb);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PMitralValve$Popen != $P$PRE$PleftHeartBurkhofWithBusConnector$PMitralValve$Popen)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._MitralValve._open from %d to %d", $P$PRE$PleftHeartBurkhofWithBusConnector$PMitralValve$Popen, $PleftHeartBurkhofWithBusConnector$PMitralValve$Popen);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PAorticValve$Popen != $P$PRE$PleftHeartBurkhofWithBusConnector$PAorticValve$Popen)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._AorticValve._open from %d to %d", $P$PRE$PleftHeartBurkhofWithBusConnector$PAorticValve$Popen, $PleftHeartBurkhofWithBusConnector$PAorticValve$Popen);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESV != $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._ventricularEndIntervals._ESV from %g to %g", $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESV, $PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESV);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESP != $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._ventricularEndIntervals._ESP from %g to %g", $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESP, $PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PESP);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDV != $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._ventricularEndIntervals._EDV from %g to %g", $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDV, $PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDV);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDP != $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._ventricularEndIntervals._EDP from %g to %g", $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDP, $PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$PEDP);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pb != $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._ventricularEndIntervals._b from %d to %d", $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pb, $PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pb);
    needToIterate = 1;
  }
  if($PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pbb != $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pbb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: leftHeartBurkhofWithBusConnector._ventricularEndIntervals._bb from %d to %d", $P$PRE$PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pbb, $PleftHeartBurkhofWithBusConnector$PventricularEndIntervals$Pbb);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmean != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmean)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._Pmean from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmean, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPmean);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSV != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._SV from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSV, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PSV);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PCO != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PCO)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._CO from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PCO, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PCO);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPs != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPs)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._Ps from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPs, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPs);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPd != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPd)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._Pd from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPd, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PPd);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._HP from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PHP);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0 != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._T0 from %g to %g", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$PT0);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryArtery$PpressureFlowMeasurement$Pb != $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryArtery._pressureFlowMeasurement._b from %d to %d", $P$PRE$PMeasurementPulmonaryArtery$PpressureFlowMeasurement$Pb, $PMeasurementPulmonaryArtery$PpressureFlowMeasurement$Pb);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmean != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmean)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._Pmean from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmean, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPmean);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSV != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._SV from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSV, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PSV);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PCO != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PCO)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._CO from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PCO, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PCO);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPs != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPs)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._Ps from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPs, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPs);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPd != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPd)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._Pd from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPd, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PPd);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._HP from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PHP);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0 != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._T0 from %g to %g", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$PT0);
    needToIterate = 1;
  }
  if($PMeasurementPulmonaryVeins$PpressureFlowMeasurement$Pb != $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementPulmonaryVeins._pressureFlowMeasurement._b from %d to %d", $P$PRE$PMeasurementPulmonaryVeins$PpressureFlowMeasurement$Pb, $PMeasurementPulmonaryVeins$PpressureFlowMeasurement$Pb);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PPmean != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PPmean)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._Pmean from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PPmean, $PMeasurementAorta$PpressureFlowMeasurement$PPmean);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PSV != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PSV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._SV from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PSV, $PMeasurementAorta$PpressureFlowMeasurement$PSV);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PCO != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PCO)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._CO from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PCO, $PMeasurementAorta$PpressureFlowMeasurement$PCO);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PPs != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PPs)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._Ps from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PPs, $PMeasurementAorta$PpressureFlowMeasurement$PPs);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PPd != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PPd)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._Pd from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PPd, $PMeasurementAorta$PpressureFlowMeasurement$PPd);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PHP != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PHP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._HP from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PHP, $PMeasurementAorta$PpressureFlowMeasurement$PHP);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$PT0 != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PT0)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._T0 from %g to %g", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$PT0, $PMeasurementAorta$PpressureFlowMeasurement$PT0);
    needToIterate = 1;
  }
  if($PMeasurementAorta$PpressureFlowMeasurement$Pb != $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementAorta._pressureFlowMeasurement._b from %d to %d", $P$PRE$PMeasurementAorta$PpressureFlowMeasurement$Pb, $PMeasurementAorta$PpressureFlowMeasurement$Pb);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PPmean != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmean)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._Pmean from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPmean, $PMeasurementCentralVeins$PpressureFlowMeasurement$PPmean);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PSV != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PSV)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._SV from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PSV, $PMeasurementCentralVeins$PpressureFlowMeasurement$PSV);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PCO != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PCO)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._CO from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PCO, $PMeasurementCentralVeins$PpressureFlowMeasurement$PCO);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PPs != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPs)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._Ps from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPs, $PMeasurementCentralVeins$PpressureFlowMeasurement$PPs);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PPd != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPd)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._Pd from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PPd, $PMeasurementCentralVeins$PpressureFlowMeasurement$PPd);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PHP != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PHP)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._HP from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PHP, $PMeasurementCentralVeins$PpressureFlowMeasurement$PHP);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$PT0 != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PT0)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._T0 from %g to %g", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$PT0, $PMeasurementCentralVeins$PpressureFlowMeasurement$PT0);
    needToIterate = 1;
  }
  if($PMeasurementCentralVeins$PpressureFlowMeasurement$Pb != $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$Pb)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MeasurementCentralVeins._pressureFlowMeasurement._b from %d to %d", $P$PRE$PMeasurementCentralVeins$PpressureFlowMeasurement$Pb, $PMeasurementCentralVeins$PpressureFlowMeasurement$Pb);
    needToIterate = 1;
  }
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  return needToIterate;
}


